server:
  port: ${APP_PORT:8082}

chat:
  name: EDC based chat application
  bpn: ${BPN:BPNL000000000000}
  datasource:
    host: ${DB_HOST:localhost}
    port: 5432
    database: ${CHAT_DB:chat_app}
    schema: public
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  edc:
    authCode: ${AUTH_CODE:password}
    assetId: ${ASSET_ID:edc-chat-app}
    policyId: ${POLICY_ID:edc-chat-policy}
    contractDefinitionId: ${CONTRACT_ID:edc-chat-contract}
    edcUrl: ${EDC_URL:http://localhost:8192}
    agreementWaitTime: ${AGREEMENT_WAIT_MILLI:7000}
    agreementRetryLimit: ${AGREEMENT_RETRY_LIMIT:5}

spring:
  application:
    name: ${chat.name}
    host: ${APP_HOST_URL:http://localhost:8082}
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: ${chat.datasource.schema}
  datasource:
    url: jdbc:postgresql://${chat.datasource.host}:${chat.datasource.port}/${chat.datasource.database}
    username: ${chat.datasource.username}
    password: ${chat.datasource.password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true

logging:
  level:
    root: INFO
